# Stage 1
FROM node:12.22.12 as node
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
# Stage 2
FROM nginx:alpine
COPY --from=node /app/dist/browser /usr/share/nginx/html
